"use client";
import { useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";
import { loadProfileData, loadProfiles, type Profile } from "../lib/weight-repository";
import { ProfileMenu } from "./profile-menu";

type Entry={date:string;weight:number}; type Node={date:string;target:number;actual?:number;future?:boolean}; type Plan={startDate:string;startWeight:number;targetDate:string;targetWeight:number};
const defaultPlan:Plan={startDate:"2026-09-01",startWeight:90.1,targetDate:"2026-12-31",targetWeight:80};
const seed:Entry[]=[{date:"2026-09-01",weight:90.1},{date:"2026-09-09",weight:90.1},{date:"2026-09-10",weight:90.1},{date:"2026-09-11",weight:90.1},{date:"2026-09-12",weight:88.5},{date:"2026-09-13",weight:89},{date:"2026-09-15",weight:89.5},{date:"2026-09-16",weight:89.6},{date:"2026-09-17",weight:88.3},{date:"2026-09-18",weight:89},{date:"2026-09-19",weight:89.6},{date:"2026-09-28",weight:90.2}];
const nodes:Node[]=[{date:"2026-09-21",target:88.4,actual:89},{date:"2026-09-28",target:87.8,actual:90.2},{date:"2026-10-05",target:87.3,future:true},{date:"2026-10-12",target:86.7,future:true}];
const days=(a:string,b:string)=>(Date.parse(b+"T00:00:00Z")-Date.parse(a+"T00:00:00Z"))/86400000;
const label=(d:string)=>new Intl.DateTimeFormat("zh-CN",{month:"short",day:"numeric",timeZone:"UTC"}).format(new Date(d+"T00:00:00Z"));
const dateKey=(date:Date)=>date.toISOString().slice(0,10);
const dateAt=(start:string,end:string,ratio:number)=>dateKey(new Date(Date.parse(start+"T00:00:00Z")+(Date.parse(end+"T00:00:00Z")-Date.parse(start+"T00:00:00Z"))*ratio));
function recentTicks(start:string,end:string){return [...new Set([start,dateAt(start,end,1/3),dateAt(start,end,2/3),end])]}
function monthlyTicks(start:string,end:string){const ticks=[start],cursor=new Date(start+"T00:00:00Z");cursor.setUTCDate(1);cursor.setUTCMonth(cursor.getUTCMonth()+1);while(dateKey(cursor)<end){ticks.push(dateKey(cursor));cursor.setUTCMonth(cursor.getUTCMonth()+1)}if(ticks.at(-1)!==end)ticks.push(end);return ticks}
function londonToday(){const parts=new Intl.DateTimeFormat("en-GB",{timeZone:"Europe/London",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date()),get=(type:string)=>parts.find(part=>part.type===type)?.value??"";return `${get("year")}-${get("month")}-${get("day")}`}
function sampledEntries(data:Entry[],limit=20){if(data.length<=limit)return data;const indexes=new Set([0,data.length-1]);for(let i=1;i<limit-1;i++)indexes.add(Math.round(i*(data.length-1)/(limit-1)));return data.filter((_,index)=>indexes.has(index))}
function futureTargets(plan:Plan,today:string){const result:{milestone_date:string;target_weight:number;status:string;is_manual:boolean}[]=[],start=new Date(plan.startDate+"T00:00:00Z"),end=new Date(plan.targetDate+"T00:00:00Z"),cursor=new Date(start);cursor.setUTCDate(cursor.getUTCDate()+((8-cursor.getUTCDay())%7||7));while(cursor<end){const date=dateKey(cursor);if(date>today){const ratio=days(plan.startDate,date)/days(plan.startDate,plan.targetDate);result.push({milestone_date:date,target_weight:Math.round((plan.startWeight+(plan.targetWeight-plan.startWeight)*ratio)*10)/10,status:"future",is_manual:false})}cursor.setUTCDate(cursor.getUTCDate()+7)}if(plan.targetDate>today)result.push({milestone_date:plan.targetDate,target_weight:plan.targetWeight,status:"future",is_manual:false});return result}

function RecentTrendChart({data,plan}:{data:Entry[];plan:Plan}){if(!data.length)return <p className="chart-empty">记录体重后，这里会显示近期变化。</p>;const w=620,h=190,p=30,start=data[0].date,end=data.at(-1)!.date,span=Math.max(1,days(start,end)),ticks=recentTicks(start,end),planTotal=Math.max(1,days(plan.startDate,plan.targetDate)),planned=(date:string)=>plan.startWeight+(plan.targetWeight-plan.startWeight)*Math.max(0,Math.min(1,days(plan.startDate,date)/planTotal)),planStart=planned(start),planEnd=planned(end),values=[...data.map(e=>e.weight),planStart,planEnd],low=Math.min(...values),high=Math.max(...values),padding=Math.max(.4,(high-low)*.18),min=low-padding,max=high+padding,x=(d:string)=>p+days(start,d)/span*(w-p*2),y=(v:number)=>p+(max-v)/(max-min)*(h-p*2),pts=data.map(e=>`${x(e.date)},${y(e.weight)}`).join(" "),mid=(min+max)/2;return <svg className="chart recent-chart" viewBox={`0 0 ${w} ${h}`} role="img" aria-label="近期实际体重与计划趋势"><line x1={p} y1={y(max)} x2={w-p} y2={y(max)} className="chart-grid"/><line x1={p} y1={y(mid)} x2={w-p} y2={y(mid)} className="chart-grid"/><line x1={p} y1={y(min)} x2={w-p} y2={y(min)} className="chart-grid"/><line x1={p} y1={y(planStart)} x2={w-p} y2={y(planEnd)} className="plan"/><polyline points={pts} className="actual"/>{sampledEntries(data).map(e=><circle key={e.date} cx={x(e.date)} cy={y(e.weight)} r="5"><title>{e.date} · 实际 {e.weight.toFixed(1)} kg</title></circle>)}{ticks.map((tick,index)=><text key={tick} x={x(tick)} y={h-4} textAnchor={index===0?"start":index===ticks.length-1?"end":"middle"}>{label(tick)}</text>)}<text x={p} y={16}>{high.toFixed(1)} kg</text></svg>}

function LongTermPlanChart({data,plan}:{data:Entry[];plan:Plan}){const w=1160,h=210,p=34,total=Math.max(1,days(plan.startDate,plan.targetDate)),ticks=monthlyTicks(plan.startDate,plan.targetDate),visible=data.filter(e=>e.date>=plan.startDate&&e.date<=plan.targetDate),latest=visible.at(-1),values=[plan.startWeight,plan.targetWeight,...visible.map(e=>e.weight)],max=Math.max(...values)+.8,min=Math.min(...values)-.8,x=(d:string)=>p+days(plan.startDate,d)/total*(w-p*2),y=(v:number)=>p+(max-v)/(max-min)*(h-p*2),pts=visible.map(e=>`${x(e.date)},${y(e.weight)}`).join(" ");return <svg className="chart plan-chart" viewBox={`0 0 ${w} ${h}`} role="img" aria-label="长期实际体重与减重计划"><line x1={p} y1={y(plan.startWeight)} x2={w-p} y2={y(plan.startWeight)} className="chart-grid"/><line x1={p} y1={y((plan.startWeight+plan.targetWeight)/2)} x2={w-p} y2={y((plan.startWeight+plan.targetWeight)/2)} className="chart-grid"/><line x1={p} y1={y(plan.targetWeight)} x2={w-p} y2={y(plan.targetWeight)} className="chart-grid"/><line x1={x(plan.startDate)} y1={y(plan.startWeight)} x2={x(plan.targetDate)} y2={y(plan.targetWeight)} className="plan"/>{visible.length>1&&<polyline points={pts} className="actual"/>}{latest&&<circle cx={x(latest.date)} cy={y(latest.weight)} r="5"><title>{latest.date} · 最新实际 {latest.weight.toFixed(1)} kg</title></circle>}<text x={p} y={16}>{plan.startWeight.toFixed(1)} kg</text><text x={w-p} y={h-18} textAnchor="end">目标 {plan.targetWeight.toFixed(1)} kg</text>{ticks.map((tick,index)=><text key={tick} x={x(tick)} y={h-4} textAnchor={index===0?"start":index===ticks.length-1?"end":"middle"}>{label(tick)}</text>)}</svg>}

export function WeightTracker(){const [entries,setEntries]=useState(seed),[milestones,setMilestones]=useState(nodes),[plan,setPlan]=useState(defaultPlan),[profiles,setProfiles]=useState<Profile[]>([]),[activeProfileId,setActiveProfileId]=useState(""),[profileBusy,setProfileBusy]=useState(true),[open,setOpen]=useState(false),[planOpen,setPlanOpen]=useState(false),[editingNode,setEditingNode]=useState<Node|null>(null),[showAllMilestones,setShowAllMilestones]=useState(false),[date,setDate]=useState(londonToday),[weight,setWeight]=useState("90.2"),[saving,setSaving]=useState(false),[notice,setNotice]=useState("正在读取共享数据…");
useEffect(()=>{void initialize()},[]);
async function initialize(){try{const list=await loadProfiles();setProfiles(list);const saved=window.localStorage.getItem("weight-active-profile"),chosen=list.find(p=>p.id===saved)??list.find(p=>p.name.toLocaleLowerCase()==="eason")??list[0];if(!chosen)throw new Error();setActiveProfileId(chosen.id);await load(chosen.id)}catch{setNotice("共享数据暂时无法读取，当前显示本地预览。")}finally{setProfileBusy(false)}}
async function load(profileId=activeProfileId){if(!profileId)return;try{const data=await loadProfileData(profileId);setEntries(data.entries);setMilestones(data.milestones);if(data.plan)setPlan(data.plan);setNotice("")}catch{setNotice("共享数据暂时无法读取，请重试。")}}
async function switchProfile(profileId:string){if(profileId===activeProfileId)return;setProfileBusy(true);try{await load(profileId);setActiveProfileId(profileId);window.localStorage.setItem("weight-active-profile",profileId);setShowAllMilestones(false)}finally{setProfileBusy(false)}}
async function profilesChanged(next:Profile[],profileId:string){setProfiles(next);setActiveProfileId(profileId);window.localStorage.setItem("weight-active-profile",profileId);setProfileBusy(true);try{await load(profileId)}finally{setProfileBusy(false)}}
const sorted=useMemo(()=>[...entries].sort((a,b)=>b.date.localeCompare(a.date)),[entries]),latest=sorted[0]??{date:plan.startDate,weight:plan.startWeight},today=londonToday(),total=days(plan.startDate,plan.targetDate),elapsed=Math.max(0,Math.min(total,days(plan.startDate,today))),time=elapsed/total*100,progress=Math.max(0,Math.min(100,(plan.startWeight-latest.weight)/(plan.startWeight-plan.targetWeight)*100)),planned=plan.startWeight+(plan.targetWeight-plan.startWeight)*elapsed/total,next=milestones.find(n=>n.future)??{date:plan.targetDate,target:plan.targetWeight,future:true};
const defaultMilestones=useMemo(()=>{const preferred=[...milestones.filter(n=>!n.future).slice(-2),...milestones.filter(n=>n.future).slice(0,3)],selected=new Set(preferred.map(n=>n.date));for(const node of milestones){if(preferred.length>=5)break;if(!selected.has(node.date)){preferred.push(node);selected.add(node.date)}}return preferred.sort((a,b)=>a.date.localeCompare(b.date))},[milestones]),visibleMilestones=showAllMilestones?milestones:defaultMilestones;
function openNewEntry(){setDate(londonToday());setOpen(true)}
async function save(e:React.FormEvent){e.preventDefault();const value=Math.round(Number(weight)*10)/10;if(!date||!Number.isFinite(value)||!activeProfileId)return;if(date>londonToday()){setNotice("不能记录未来日期的体重，请选择今天或过去的日期。");return}setSaving(true);const {error}=await supabase.from("weight_entries").upsert({profile_id:activeProfileId,entry_date:date,weight:value},{onConflict:"profile_id,entry_date"});setSaving(false);if(error){setNotice("保存失败，请检查网络后重试。");return}await load();setOpen(false);setNotice("体重记录已保存。");window.setTimeout(()=>setNotice(""),2400)}
async function savePlan(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget),nextPlan={startDate:String(form.get("startDate")),startWeight:Number(form.get("startWeight")),targetDate:String(form.get("targetDate")),targetWeight:Number(form.get("targetWeight"))};if(nextPlan.targetDate<=nextPlan.startDate||nextPlan.targetWeight>=nextPlan.startWeight){setNotice("请确保目标日期晚于开始日期，且目标体重低于初始体重。");return}setSaving(true);const {error}=await supabase.from("weight_plan").upsert({profile_id:activeProfileId,start_date:nextPlan.startDate,start_weight:nextPlan.startWeight,target_date:nextPlan.targetDate,target_weight:nextPlan.targetWeight},{onConflict:"profile_id"});if(!error){await supabase.from("weight_milestones").delete().eq("profile_id",activeProfileId).gt("milestone_date",today);const generated=futureTargets(nextPlan,today).map(row=>({...row,profile_id:activeProfileId}));if(generated.length)await supabase.from("weight_milestones").insert(generated)}setSaving(false);if(error){setNotice("计划保存失败，请重试。");return}setPlanOpen(false);await load();setNotice("减重计划已更新；已结算节点保持不变。");}
async function saveNode(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!editingNode)return;const target=Number(new FormData(e.currentTarget).get("target"));setSaving(true);const {error}=await supabase.from("weight_milestones").update({target_weight:target,is_manual:true}).eq("profile_id",activeProfileId).eq("milestone_date",editingNode.date).eq("status","future");setSaving(false);if(error){setNotice("节点保存失败，请重试。");return}setEditingNode(null);await load();setNotice("未来节点已更新。");}
async function removeEntry(entryDate:string){if(!window.confirm(`删除 ${entryDate} 的体重记录吗？`))return;const {error}=await supabase.from("weight_entries").delete().eq("profile_id",activeProfileId).eq("entry_date",entryDate);if(error){setNotice("删除失败，请重试。");return}await load();setNotice("体重记录已删除。");}
return <main className="shell">
{notice&&<div className="notice" role="status">{notice}</div>}
<header><div><p className="eyebrow">WEIGHT JOURNEY</p><h1>减重进度</h1></div><div className="actions"><ProfileMenu profiles={profiles} activeProfileId={activeProfileId} busy={profileBusy} onSelect={id=>void switchProfile(id)} onProfilesChanged={(next,id)=>void profilesChanged(next,id)} onNotice={setNotice}/><button className="text" onClick={()=>setPlanOpen(true)}>编辑计划</button><button className="primary desktop" onClick={openNewEntry}>＋ 记录体重</button></div></header>
<section className="hero"><div className="ring" style={{"--value":`${Math.max(1,progress)}%`} as React.CSSProperties}><div><b>{progress.toFixed(0)}%</b><span>减重目标进度</span></div></div><div className="hero-copy"><p className="eyebrow">本轮减重计划</p><h2>距离 {plan.targetWeight.toFixed(1)} kg 还有 {(latest.weight-plan.targetWeight).toFixed(1)} kg</h2><p>从 {plan.startWeight.toFixed(1)} kg 开始 · {plan.startDate}—{plan.targetDate}</p><div className="progress"><div className="progress-top"><span>计划与实际进度</span><b>实际 {progress.toFixed(0)}% / 时间 {time.toFixed(1)}%</b></div><div className="rail"><i className="time" style={{width:`${time}%`}}/><i className="weight" style={{width:`${Math.max(.7,progress)}%`}}/></div><div className="scale"><span>{label(plan.startDate)}</span><span>{label(plan.targetDate)}</span></div><strong className="lag">当前高于计划体重 {(latest.weight-planned).toFixed(1)} kg</strong></div></div></section>
<section className="stats"><article><span>当前体重</span><b>{latest.weight.toFixed(1)} kg</b></article><article><span>已进行</span><b>{elapsed} / {total} 天</b></article><article><span>下一节点 · {label(next.date)}</span><b>{next.target.toFixed(1)} kg</b></article></section><button className="primary mobile" onClick={openNewEntry}>＋ 记录今天体重</button>
<section className="grid"><article className="panel trend-panel"><div className="panel-title"><div><p className="eyebrow">趋势</p><h3>近期趋势</h3></div><div className="legend"><span><i className="actual-key"/>实际</span><span><i className="plan-key"/>计划</span></div></div><div className="chart-heading"><span>{entries.length} 次记录</span></div><RecentTrendChart data={[...sorted].reverse()} plan={plan}/></article><article className="panel milestones"><div className="panel-title"><div><p className="eyebrow">里程碑</p><h3>每周节点</h3></div><span>未来节点可编辑</span></div><div>{visibleMilestones.map(n=><div className="node" key={n.date}><i className={n.future?"dot future":"dot miss"}/><div><b>{label(n.date)}</b><span>目标 {n.target.toFixed(1)} kg</span></div><div className="result">{n.future?<button className="node-edit" onClick={()=>setEditingNode(n)}>编辑</button>:<><b>{n.actual?.toFixed(1)}</b><span className="missed">未完成</span></>}</div></div>)}</div>{milestones.length>5&&<button className="milestone-toggle" onClick={()=>setShowAllMilestones(value=>!value)}>{showAllMilestones?"收起目标":`查看全部目标（${milestones.length}）`}</button>}</article></section>
<section className="panel long-plan"><div className="panel-title"><div><p className="eyebrow">计划</p><h3>长期计划</h3></div><div className="legend"><span><i className="actual-key"/>实际</span><span><i className="plan-key"/>计划</span><span>{plan.targetWeight.toFixed(1)} kg 目标</span></div></div><LongTermPlanChart data={[...sorted].reverse()} plan={plan}/></section>
<section className="panel records"><div className="panel-title"><div><p className="eyebrow">日志</p><h3>体重记录</h3></div><span>共 {entries.length} 条</span></div>{sorted.map((e,i)=>{const old=sorted[i+1],delta=old?e.weight-old.weight:0;return <div className="record" key={e.date}><b>{e.date}</b><span>{e.weight.toFixed(1)} kg</span><span className={delta>0?"up":"down"}>{old?`${delta>0?"+":""}${delta.toFixed(1)} kg`:"起始"}</span><div className="row-actions"><button onClick={()=>{setDate(e.date);setWeight(e.weight.toFixed(1));setOpen(true)}}>编辑</button><button className="danger" onClick={()=>void removeEntry(e.date)}>删除</button></div></div>})}</section>
{open&&<div className="backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><form className="dialog" onSubmit={save}><button type="button" className="close" onClick={()=>setOpen(false)} aria-label="关闭">×</button><p className="eyebrow">DAILY CHECK-IN</p><h2>记录体重</h2><label>日期<input type="date" value={date} max={today} onChange={e=>setDate(e.target.value)} required/></label><label>体重（kg）<input type="number" min="20" max="400" step="0.1" inputMode="decimal" value={weight} onChange={e=>setWeight(e.target.value)} required/></label><p>同一天只保留一条记录，再次保存会覆盖原数据。</p><button className="primary" type="submit" disabled={saving}>{saving?"正在保存…":"保存记录"}</button></form></div>}
{planOpen&&<div className="backdrop"><form className="dialog" onSubmit={savePlan}><button type="button" className="close" onClick={()=>setPlanOpen(false)} aria-label="关闭">×</button><p className="eyebrow">WEIGHT PLAN</p><h2>编辑减重计划</h2><div className="form-grid"><label>开始日期<input name="startDate" type="date" defaultValue={plan.startDate} required/></label><label>初始体重<input name="startWeight" type="number" step="0.1" defaultValue={plan.startWeight} required/></label><label>目标日期<input name="targetDate" type="date" defaultValue={plan.targetDate} required/></label><label>目标体重<input name="targetWeight" type="number" step="0.1" defaultValue={plan.targetWeight} required/></label></div><p>已经结算的历史节点会保持不变。</p><button className="primary" disabled={saving}>{saving?"正在保存…":"保存计划"}</button></form></div>}
{editingNode&&<div className="backdrop"><form className="dialog" onSubmit={saveNode}><button type="button" className="close" onClick={()=>setEditingNode(null)} aria-label="关闭">×</button><p className="eyebrow">WEEKLY MILESTONE</p><h2>编辑 {label(editingNode.date)} 节点</h2><label>目标体重（kg）<input name="target" type="number" step="0.1" defaultValue={editingNode.target} required/></label><button className="primary" disabled={saving}>{saving?"正在保存…":"保存节点"}</button></form></div>}
</main>}
